# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NuGet Package Release Build

on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
    types:
      - opened
    branches:
      - 'releases/**'

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: '5.12.0'

    - name: Generate version json
      run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          dotnet gitversion /output json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

    - name: Harvest version variables
      run: |
          echo 'N2H_BUILD_NUMBER=${{ env.BUILD_NUMBER }}' >> $GITHUB_ENV
          echo 'N2H_MAJOR_MINOR_PATCH=${{ fromJson(env.PACKAGE_JSON).MajorMinorPatch }}' >> $GITHUB_ENV
          echo 'N2H_PRERELEASE_LABEL=${{ fromJson(env.PACKAGE_JSON).PreReleaseLabel }}.${{ env.BUILD_NUMBER }}' >> $GITHUB_ENV
          echo 'N2H_SHORT_SHA=${{ fromJson(env.PACKAGE_JSON).ShortSha }}' >> $GITHUB_ENV
      env:
        BUILD_NUMBER: ${{ github.run_number }}-${{ github.run_attempt }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
          dotnet build --no-restore --configuration Release -p:VersionPrefix=${{ env.N2H_MAJOR_MINOR_PATCH }} --version-suffix ${{ env.N2H_PRERELEASE_LABEL }} -p:InformationalVersion=${{ env.N2H_MAJOR_MINOR_PATCH }}-${{ env.N2H_PRERELEASE_LABEL }}+${{ env.N2H_SHORT_SHA }}

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Pack
      run: |
          dotnet pack ./Net2HassMqtt/Net2HassMqtt.csproj --no-build --no-restore --configuration Release -p:VersionPrefix=${{ env.N2H_MAJOR_MINOR_PATCH }} --version-suffix ${{ env.N2H_PRERELEASE_LABEL }}


    - name: Archive NuGet package
      uses: actions/upload-artifact@v4
      with:
        name: nuget-package
        path: Net2HassMqtt/bin/**/*.nupkg
        compression-level: 0
        if-no-files-found: error


